Memory watch
Sekanor/SM63PracticeHack pull request #40
Opened 2020-11-19 22:17 UTC by GTcreyon

2020-11-20 17:03 UTC, Sekanor reviewed
Also it'd be better if this branch could be merged into `dev` and not into `display` since those branches aren't linked together, but I guess I'll see that when I merge

2020-11-20 17:04 UTC, Sekanor requested changes

2020-11-20 17:04 UTC, Sekanor commented on src/classes/TextManager.as
> +        {
How many rows are available now? I guess that number can be changed?

2020-11-20 17:04 UTC, Sekanor commented on docs/Commands.md
> +
similarly; `removewatch`?

2020-11-20 17:04 UTC, Sekanor commented on docs/Commands.md
> +
Maybe `watchvar` or `watch` instead? I feel like both of these convey the idea pretty well (and we are only watching variables anyways)

2020-11-21 20:10 UTC, GTcreyon commented on src/classes/TextManager.as
> +        {
As many rows as required, technically, but the memory watch just uses '\n' at the end of each entry.

2020-11-21 20:42 UTC, Sekanor commented on src/classes/TextManager.as
> +        {
Okay, we'll let this system until another command wants one of these rows (if that ever happens).

2020-11-22 00:43 UTC, Sekanor approved these changes

2020-11-22 00:43 UTC, merged